spring.application.name=doc_intel

###### Kafka Configuration ########

spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=PLAIN

# Add this environment variable to intelligence ->
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${TEST_USER}" password="${USER_TESTER_PASSWORD}";


### Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

### Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.doc_intel.DTO

### Postgres SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/document_db
spring.datasource.username=admin
spring.datasource.password=DocIntel@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata