spring.application.name=doc_intel
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

## Store Configuration
vector.data.store=OPEN_STORE
#vector.data.store=IN_MEMORY

####################################################################################################
###### Kafka Configuration ########
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=PLAIN

# Add this environment variable to intelligence ->
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${TEST_USER}" password="${USER_TESTER_PASSWORD}";

### Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

### Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.doc_intel.DTO


####################################################################################################
### Postgres SQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

####################################################################################################
### MinIO Configuration
MINIO.ROOT.USER=${MINIO_ROOT_USER}
MINIO.ROOT.PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO.BUCKET.KEY=${MINIO_BUCKET_KEY}
MINIO.HOST.URL=${MINIO_HOST_URL}

####################################################################################################
### Open Search Configuration
OPEN.SEARCH.ROOT.USER=${OPENSEARCH_USERNAME}
OPEN.SEARCH.ROOT.PASSWORD=${OPENSEARCH_PASSWORD}
OPEN.SEARCH.PORT=${OPENSEARCH_PORT}
OPEN.SEARCH.HOST=${OPENSEARCH_HOST}

#logging.level.org.springframework.security=DEBUG
jwt.secret=${JWT_SECRET}